root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/main ./cmd/gateway"
bin = "tmp/main"
delay = 1000

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true

[misc]
  clean_on_exit = true  