version: "3.9"

services:
  postgres:
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile.postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rahasia
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/infra/db/migrations/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - local-app-network

  redis:
    image: redis:7.2.7-alpine3.21
    ports:
      - "6379:6379"
    networks:
      - local-app-network

  redisinsight:
    image: redislabs/redisinsight:2.50
    ports:
      - "5540:5540"
    networks:
      - local-app-network

  rabbitmq:
    image: rabbitmq:4.0.5-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - local-app-network

  gateway:
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - local-app-network

volumes:
  postgres_data:
  
networks:
  local-app-network:
    driver: bridge